### ISSUE TITLE
Crash to server join page, on join with rebreather, when under water

### ISSUE THREAD

**Issue by CanadianHarp85** [Crimix/More-Gadgets#2]
https://pastebin.com/KKiSK8yp

**Comment by Crimix** [comment]
Thank you for the bug report. I will look into fixing this.
Just one question, which version of Forge were you using?

**Comment by CanadianHarp85** [comment]
MC 1.12.2
forge-14.23.5.2838
Running Win 10, 64-bit -in case any of that is helpful as well. I can confirm I did restart the server and attempt connection, as well as I tried to kick/kill upon joining. The error happens too quickly for console to send after join but before glitch.
Initially it happened the moment I went under water, which kicked me immediately. There was no freezing first.

**Comment by Crimix** [comment]
Thank you, I will look into why it happens and fix it.

**Comment by Crimix** [comment]
I have now fixed the issue and submitted a new version for approval on CursForge. So you can soon get the fixed version
